# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\x12\x04\x63\x61lc\" \n\x08\x42inaryOp\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\'\n\tBinaryMat\x12\x0c\n\x04mat2\x18\x01 \x03(\x01\x12\x0c\n\x04mat1\x18\x02 \x03(\x01\"\x1a\n\tResultMat\x12\r\n\x05value\x18\x01 \x03(\x01\"\x17\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\x01\x32\xa7\x01\n\nCalculator\x12#\n\x03\x41\x64\x64\x12\x0e.calc.BinaryOp\x1a\x0c.calc.Result\x12#\n\x03Mul\x12\x0e.calc.BinaryOp\x1a\x0c.calc.Result\x12#\n\x03\x44iv\x12\x0e.calc.BinaryOp\x1a\x0c.calc.Result\x12*\n\x06MatMul\x12\x0f.calc.BinaryMat\x1a\x0f.calc.ResultMatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BINARYOP']._serialized_start=20
  _globals['_BINARYOP']._serialized_end=52
  _globals['_BINARYMAT']._serialized_start=54
  _globals['_BINARYMAT']._serialized_end=93
  _globals['_RESULTMAT']._serialized_start=95
  _globals['_RESULTMAT']._serialized_end=121
  _globals['_RESULT']._serialized_start=123
  _globals['_RESULT']._serialized_end=146
  _globals['_CALCULATOR']._serialized_start=149
  _globals['_CALCULATOR']._serialized_end=316
# @@protoc_insertion_point(module_scope)
